{
  "template_name":"基础及屈光检查",
  "content_resource_id":"xxxxxx_id",
  "data_groups":[{
    "type":"data_grup",
    "group_id":"001",
    "group_code":"jcjc",
    "group_key":"jcjc",
    "group_title":"基础检查",
    "items":[
        {
        "id":"item1",
        "title":"裸眼视力",
        "key":"lysl",
        "unit":"度",
        "required":"true",
        "items":[
          {
            "id":"item12",
            "title":"od",
            "key":"od",
            "unit":"度",
            "required":"true"
          },
          {
            "id":"item13",
            "title":"os",
            "key":"os",
            "unit":"度",
            "required":"true"
          },
          {
            "id":"item14",
            "title":"ou",
            "key":"ou",
            "unit":"度",
            "required":"true"
          }]
        },
        {
        "id":"item2",
        "title":"原镜视力",
        "key":"yjsl",
        "unit":"度",
        "required":"true",
        "items":[
          {
            "id":"item21",
            "title":"od",
            "key":"od",
            "unit":"度",
            "required":"true"
          },
          {
            "id":"item22",
            "title":"os",
            "key":"os",
            "unit":"度",
            "required":"true"
          },
          {
            "id":"item23",
            "title":"ou",
            "key":"ou",
            "unit":"度",
            "required":"true"
          }
        ]
        }
    ]}
  ],
  "enable":"true"
}
